name: Destroy microservice-eks project

on: workflow_dispatch
env :
  EKS_DIR: terraform/eks
  MONITORING_DIR: terraform/monitoring
  CLUSTER_NAME: my-eks-cluster-v2
  MICROSERVICE_MANIFEST_URL: https://raw.githubusercontent.com/pavi550/microservices-demo/main/release/kubernetes-manifests.yaml
  HPA_NAMESPACE: default
  TF_VERSION: 1.14.9

jobs:
  microservice:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2
    - name: configure AWS cli
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region us-east-1
        kubectl get nodes
        kubectl get namespaces
    - name: Delete example microservice manifests
      run: kubectl delete -f ${{ env.MICROSERVICE_MANIFEST_URL }} --ignore-not-found=true

    - name: Delete autoscaling policies
      run: kubectl delete hpa --all -n ${{ env.HPA_NAMESPACE }} --ignore-not-found=true

    - name: Check Deployment status
      run: kubectl get all -o wide -A

  terraform_monitoring:
    needs: microservice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2
    - name: configure AWS cli
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      working-directory: ${{ env.MONITORING_DIR }}
      run: terraform init
    - name: Terraform destroy
      working-directory: ${{ env.MONITORING_DIR }}
      run: terraform destroy -auto-approve

  terraform_destroy_microservice:
    needs: terraform_monitoring
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: configure AWS cli
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      working-directory: ${{ env.EKS_DIR }}
      run: terraform init
    - name: Terraform destroy
      working-directory: ${{ env.EKS_DIR }}
      run: terraform destroy -auto-approve
